ALTER TABLE hospitals ADD COLUMN status VARCHAR(50) DEFAULT 'PENDING_CONFIRMATION';
ALTER TABLE hospitals ADD COLUMN invitation_token VARCHAR(255);
ALTER TABLE hospitals ADD COLUMN token_expiry TIMESTAMP;