ALTER TABLE hospitals ALTER COLUMN manager_id DROP NOT NULL;
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'PENDING_CONFIRMATION';
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS temp_manager_email VARCHAR(255);
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS invitation_token VARCHAR(255);
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS token_expiry TIMESTAMP;