ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_code VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_expiry TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_enabled BOOLEAN DEFAULT FALSE;