spring.profiles.active=local
spring.application.name=healthcare-connect
spring.datasource.driver-class-name=org.postgresql.Driver
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# Database
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.flyway.clean-disabled=false
spring.flyway.validate-on-migrate=false

# JPA & Flyway
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
logging.level.org.hibernate.SQL=DEBUG

## Mail (mailtrap)
#spring.mail.host=sandbox.smtp.mailtrap.io
#spring.mail.port=2525
#spring.mail.username=${MAIL_USERNAME}
#spring.mail.password=${MAIL_PASSWORD}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

# Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.auth=true

#Cloud
cloudinary.cloud-name=${CLOUD_NAME}
cloudinary.api-key=${CLOUD_API_KEY}
cloudinary.api-secret=${CLOUD_API_SECRET}

#RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBIT_USERNAME}
spring.rabbitmq.password=${RABBIT_PASSWORD}

# ================= RETRY =================
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.max-retries=3
spring.rabbitmq.listener.simple.retry.initial-interval=2000
spring.rabbitmq.listener.simple.multiple=true
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.listener.simple.retry.republish-to-dlx=true

# ================= ACK =================
spring.rabbitmq.listener.simple.acknowledge-mode=auto

# ================= MOMO =================
momo.partner-code=${PARTNER_CODE}
momo.access-key=${ACCESS_KEY}
momo.secret-key=${SECRET_KEY}
momo.endpoint=${ENDPOINT}
momo.return-url=${RETURN_URL}
momo.notify-url=${NOTIFY_URL}
